### ISSUE TITLE
Newest r-terra build not available

### ISSUE THREAD

**Issue by TMondain** [conda-forge/r-terra-feedstock#58]
### Comment:

Hi! It seems that the latest r-terra builds are failing. Do you have any idea whether you might be able to fix it please? Cheers
Thomas

**Comment by mfansler** [comment]
This has been a problem for a while. This and a couple other packages that use [the `rwinlib` vendoring](https://github.com/rwinlib) for GDAL and PROJ have broken Windows builds. There was an attempt to swap out the vendoring in one of these (https://github.com/conda-forge/r-sf-feedstock/pull/84), but that stalled out.

Potentially, we could temporarily skip the Windows builds and shift this to be a Windows-only issue. I think this makes sense since we are also starting to accumulate some downstream dependencies that can't build without newer `r-terra` builds.

@xhochy did you have thoughts about this? While I'd like to help, I won't have the bandwidth for at least a week.

**Comment by TMondain** [comment]
Thank you very much for looking into it. I don't think there's anything I can realistically do to help (as I am pretty inexperienced with this kind of thing) but please let me know if there is anything. Like you say, I actually need the updated version because it's a dependency for another package.

**Comment by mfansler** [comment]
@TMondain could you be more specific as to what you require? What downstream package? What platform do you need?

**Comment by TMondain** [comment]
Sorry, that was quite vague! I need to install the development version of the biomod2 package from github (https://biomodhub.github.io/biomod2/index.html) and it needs terra >1.6 to work. I'm not entirely sure what you mean by platform, I'm afraid.

**Comment by mfansler** [comment]
@TMondain platforms: Linux, Windows, macOS. I'm just wondering if you are on Windows or not. 

We could easily get `r-terra >=1.6` builds released almost immediately for everything except Windows, but I've been reluctant to go that route. If you need it for Linux or macOS, then that incentivizes that choice.

**Comment by TMondain** [comment]
@mfansler, ah yeah, I'm being an idiot. I'm using Linux so my problem would be solved fairly easily but I understand if you want to be able to roll it out across all platforms!

**Comment by TMondain** [comment]
Hi @mfansler, sorry to chase you up, but is there any update on whether it would be possible to roll out the linux version of rterra please?

**Comment by mfansler** [comment]
I have a few more things I want to try with the Windows build (working on https://github.com/conda-forge/r-terra-feedstock/pull/60), but if I can't get it working today, I'll drop it and let the other builds free.

**Comment by TMondain** [comment]
That's great, thank you very much
